/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game_score_board;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author rajiv
 */
public class Create_account_page extends javax.swing.JFrame {

    /**
     * Creates new form Create_account_page
     */
    public Create_account_page() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        this.setSize(800, 500);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pf1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create account");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game_score_board/xgames.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 80, 386, 328));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LoginId");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 56, 103, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Registration Page");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 13, 169, 36));
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 58, 136, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 98, 103, -1));
        jPanel2.add(pf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 100, 136, 23));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 234, 150, 60));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Email ID");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 141, 103, -1));
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 143, 136, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Contact Number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 183, 156, -1));
        jPanel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 185, 136, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Choose at least 1 game:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 312, 237, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("DOTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 133, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("CSGO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 362, 133, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 420, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean supress_code=true;
boolean supress_1=true;
boolean supress_2=true;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String url = "jdbc:sqlite:C:\\Rajiv\\SQL\\Sqlite\\game_database.db";
Connection conn = null;
try {
    conn = DriverManager.getConnection(url);
    }
catch (SQLException e) {
    System.out.println(e.getMessage());
    }

int ID=Integer.parseInt(t1.getText());
char[] pas=pf1.getPassword();
String password="";
for(int i=0;i<pas.length;i++)
    password+=pas[i];
int c_no=Integer.parseInt(t6.getText());     
String email=t5.getText();
if(supress_code==true){
 
String sql="INSERT INTO login_details VALUES("+ID+",'"+password+"','"+email+"',"+c_no+");";
        try
        {
            Statement stmt=conn.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Successfully registered");
            JOptionPane.showMessageDialog(null, "You have been succesfully registered");
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
        supress_code=false;
}/*
int flag=1;
String gameid="";
if(supress_1==true){
if(r1.isSelected()==true)
{
    gameid=t7.getText();
    String sql_gameid = "SELECT gameid FROM login_gameID where game_no=1";
try
{
    Statement stmt1=conn.createStatement();
    ResultSet rs    = stmt1.executeQuery(sql_gameid);
    while (rs.next())
    {
        if(gameid.equals(rs.getString("gameid")))
        {
            flag=0;
            JOptionPane.showMessageDialog(null,"This gameID (1) is already taken!");
            t7.setText(null);
            break;
        }
    }
    
}
catch(SQLException  e)
        {
            System.out.println(e.getMessage());
        }
if (flag==1)
{
    String sql="INSERT INTO login_gameID VALUES("+ID+",'"+gameid+"',1);";
    try
        {
            Statement stmt=conn.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Game1 registered");
            supress_1=false;
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
}}}
flag=1;
if(supress_2==true){
if(r2.isSelected()==true)
{
    gameid=t8.getText();
    String sql_gameid = "SELECT gameid FROM login_gameID where game_no=2";
try
{
    Statement stmt1=conn.createStatement();
    ResultSet rs    = stmt1.executeQuery(sql_gameid);
    while (rs.next())
    {
        if(gameid.equals(rs.getString("gameid")))
        {
            flag=0;
            JOptionPane.showMessageDialog(null,"This gameID (2) is already taken!");
            t8.setText(null);
            break;
        }
    }
    
}
catch(SQLException  e)
        {
            System.out.println(e.getMessage());
        }
if (flag==1)
{
    String sql="INSERT INTO login_gameID VALUES("+ID+",'"+gameid+"',2);";
    try
        {
            Statement stmt=conn.createStatement();
            stmt.executeUpdate(sql);
            System.out.println("Game2 registered");
            supress_2=false;
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }
}}}

try{
conn.close();}
catch(Exception e)// TODO add your handling code here:
{System.out.println(e.getMessage());}*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
String url = "jdbc:sqlite:C:\\Rajiv\\SQL\\Sqlite\\game_database.db";
Connection conn = null;
try {
    conn = DriverManager.getConnection(url);
    }
catch (SQLException e) {
    System.out.println(e.getMessage());
    }
String sql_login = "SELECT loginid FROM login_details";
int last_donor_id=1000;
try
{
    Statement stmt1=conn.createStatement();
    ResultSet rs    = stmt1.executeQuery(sql_login);
    while (rs.next())
    {
        last_donor_id=rs.getInt("loginid");
    }
    conn.close();
}
catch(SQLException  e)
        {
            System.out.println(e.getMessage());
        } 
t1.setText(String.valueOf(last_donor_id+1));        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();
new DOTA_signup(Integer.parseInt(t1.getText())).setVisible(true); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
new CSGO_Registration(t1.getText()).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_account_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_account_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
